about sound events, enabling a better interpretation of the information encoded in the input features.

### _Metrics_

To evaluate our models, we adopted the official metrics of the DCASE 2024 Task 3 Challenge [11] that are based on true positive (TP) and false positive (FP) predictions. A prediction is considered TP if the class prediction is correct and if its predicted DOA is within \(\pm 20^{\circ}\) from the target, and the relative distance error (\(RDE\)=\(|L_{p}-L_{r}|/L_{r}\) with \(L_{p}\) and \(L_{r}\) being the predicted and reference distance, respectively) is smaller than 1. Metrics are computed at the frame level and for each class independently and then averaged across the number of classes. Based on these, the adopted metrics are the class- and location-dependent F1 score (\(F_{\leq 20^{\circ}/1}\)), the class-dependent DOA error (\(DOAE\)), and the class-dependent relative distance error (\(RDE\)) [11]. We also include the \(SELD\) score that encodes the overall 3D SELD performance and is achieved as: \(SELD\)=\(\mathrm{mean}((1-F_{\leq 20^{\circ}/1}),DOAE/180,RDE)\).

### _Hyper-parameters and Experimental Settings_

We trained our models using 3-second audio chunks, extracted every 1 s for training and without overlap for testing. Spectrograms were generated via STFT with a 512-point Hann window and 150-sample hop size, yielding 480 temporal bins for 24kHz audio. Log-mel spectrograms (128 frequency bins) were computed for audio channels, DRR, D+R, and IV features. For stpACC features, we applied an STFT with a 1014-point Hann window. This ensures that, when considering only the positive time-lags \(\tau\)\(>\) 0, \(stpACC(t,\tau)\) contains 512 time-lag bins, covering delays up to approximately 20 ms after the direct sound. We then downsample the time-lag dimension by a factor of 4 to achieve 128 bins and allow concatenation with the other features. Models were trained with batch size 32 using Adam optimizer for 50 epochs, selecting the best based on the lowest SELD score. The learning rate was 5e-5 for 30 epochs, then reduced by 5% per epoch.

### _Results_

The results obtained using the proposed distance features are presented in Table II. Confidence intervals were estimated using the jackknife estimate of variance [36], applying the leave-one-out resampling technique to each of the 78 sequences in the test set. The table shows that all tested distance features contributed to a reduction in \(RDE\), leading to an overall improvement in \(SELD\) score. A small but not significant improvement was observed in \(F_{\leq 20^{\circ}/1}\). This is expected, as the distance features are specifically designed to enhance distance estimation, while the TP predictions used to compute \(F_{\leq 20^{\circ}/1}\) depend on an \(RDE\)\(<\)1 threshold, which is a relatively trivial condition to meet even without distance features.

The model without distance features achieved the lowest \(DOAE\). However, considering the confidence intervals, this difference appears to fall within statistical noise. Nevertheless, the \(DOAE\) confidence interval obtained with stpACC features is over three times larger than that of the other features, indicating greater variability and noisier estimates for this metric. Despite this, stpACC features also yielded the best \(RDE\) and the highest \(SELD\) score. While DRR is a known indicator in distance perception [19, 22, 37, 38], D+R features yielded better distance estimates. We hypothesize that the model benefits from greater flexibility in learning task-relevant information from the direct and reverberant components separately.

## IV Conclusion

This paper introduces novel distance input features for 3D SELD, leveraging reverberation cues encoded in the audio signal. The first category of proposed features separates direct and reverberant components, which are either fed to the model independently or represented as a direct-to-reverberant ratio. The second category aims to enhance the model's understanding of early reflections, particularly the first reflection.

Experiments on STARSS23 indicate that the proposed features improve distance estimation, leading to enhanced overall SELD score. The most significant improvement was observed with short-term power of the autocorrelation features. Future research will explore the effectiveness of reverberation-based distance features across different 3D SELD data, including synthetic data, and various network architectures.

\begin{table}
\begin{tabular}{c|c|c|c|c} \hline
**Distance Features** & \(F_{\leq 20^{\circ}/1}\) \(\uparrow\) & \(DOAE\) \(\downarrow\) & \(RDE\) \(\downarrow\) & \(SELD\) \(\downarrow\) \\ \hline None & 34.7\% (29.7\% - 39.3\%) & **19.4**\({}^{\circ}\) (16.6\({}^{\circ}\)-22.2\({}^{\circ}\)) & 0.296 (0.273 - 0.355) & 0.352 (0.332 - 0.385) \\ \hline D+R & **36.4\%** (31.1\% - 41.6\%) & 22.0\({}^{\circ}\) (18.6\({}^{\circ}\)-24.2\({}^{\circ}\)) & 0.273 (0.234 - 0.298) & 0.344 (0.314 - 0.367) \\ \hline DRR & 36.0\% (30.8\% - 41.4\%) & 20.1\({}^{\circ}\) (17.7\({}^{\circ}\)-23.4\({}^{\circ}\)) & 0.286 (0.240 - 0.315) & 0.346 (0.319 - 0.568) \\ \hline stpACC & 35.9\% (30.5\% - 41.2\%) & 21.3\({}^{\circ}\) (11.9\({}^{\circ}\)-30.6\({}^{\circ}\)) & **0.262** (0.225 - 0.296) & **0.341** (0.304 - 0.375) \\ \hline \end{tabular}
\end{table} TABLE II: Result with respective 95% confidence intervals achieved with the proposed distance input features. Each row represents a model trained using the concatenation of log-mel spectrograms, intensity vectors (IVs), and the different distance features. For the first row (“None”), only log-mel spectrograms and IVs are employed.

Fig. 4: Distance features with respective log mel spectrogram extracted from a sequence of STARSS23.

