Smith, Robert Kern, Matti Picus, Stephan Hoyer, Marten H. van Kerkwijk, Matthew Brett, Allan Haldane, Jaime Fernandez del Rio, Mark Wiebe, Pearu Peterson, Pierre Gerard-Marchant, Kevin Sheppard, Tyler Reddy, Warren Weckesser, Hamner Abbasi, Christoph Gohlke, and Travis E. Oliphant, "Array programming with NumPy," _Nature_, vol. 585, no. 7825, pp. 357-362, Sept. 2020.
* [3] Harrison Chase, "LangChain," Oct. 2022.
* [4] S. Lee, M.A. Martinez-Ramirez, W.-H. Liao, S. Uhlich, G. Fabbro, K. Lee, and Y. Mitsufuji, "GRAFX: AN OPEN-SOURCE LIBRARY FOR AUDIO PROCESSING GRAPHS IN PYTORCH," 2024, pp. 475-478.
* 2022 IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)_. IEEE, may 23 2022, pp. 6982-6986.
* 5671, 2021.
* [7] K.W. Cheuk, H. Anderson, K. Agres, and D. Herremans, "NnAudio: An on-the-Fly GPU Audio to Spectrogram Conversion Toolbox Using 1D Convolutional Neural Networks," _IEEE Access_, vol. 8, pp. 161981-162003, 2020.
* [8] Muhammad Aitessam Ahmed, "Design and development of audio processing and speech recognition algorithm," 2021.
* [9] J. Ramaiah and R. Gannavarpu, "Dynamic fringe analysis using GPU assisted root-MUSIC method," 2020, vol. 11552.
* [10] M. Bucurica, I. Dogaru, and R. Dogaru, "Improving computational efficiency for implementing a sound propagation simulation environment using Python & GPU," 2017.
* [11] B. Fontaine, D.F.M. Goodman, V. Benichoux, and R. Brette, "Brian hears: Online auditory processing using vectorization over channels," _Frontiers in Neuroinformatics_, vol. 5, 2011.
* [12] Jeff Hwang, Moto Hira, Caroline Chen, Xiaohui Zhang, Zhaoheng Ni, Guangzhou Sun, Pingchuan Ma, Ruizhe Huang, Vineel Pratap, Yuekai Zhang, Anurag Kumar, Chin-Yun Yu, Chuang Zhu, Chunxi Liu, Jacob Kahn, Mirco Ravanelli, Peng Sun, Shinji Watanabe, Yangyang Shi, and Yumeng Tao, "Torchaudio 2.1: Advancing speech recognition, self-supervised learning, and audio processing components for pytorch," in _2023 IEEE Automatic Speech Recognition and Understanding Workshop (ASRU)_, 2023, pp. 1-9.
* [13] Brian McFee, Colin Raffel, Dawen Liang, Daniel Ellis, Matt Mcvicar, Eric Battenberg, and Oriol Nieto, _librosa: Audio and Music Signal Analysis in Python_, Jan. 2015, Pages: 24.
* [14] The MathWorks Inc., "Matlab version: 9.13.0 (r2022b)," 2022.

