version: '3.8'

services:
  drive-authenticator:
    image: marcomorandinunitn/ai-design-google-authenticator:latest
    ports:
      - "8000:5000"
    environment:
      - ENVIRONMENT=production
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - AUTH_SERVICE_PORT=5000
      - BASE_URL=${BASE_URL}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    volumes:
      - ./ssl:/app/ssl  # Mount SSL certificates if needed
    restart: unless-stopped
    networks:
      - app-network
    # Add healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge