version: '3.8'

services:
  summarization-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: summarization-agent:${VERSION:-latest}
    container_name: summarization-agent
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s