version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  agent-registry:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - REGISTRY_PORT=8080
      - REGISTRY_HOST=0.0.0.0
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=agent_registry
      - MONGODB_COLLECTION=agents
      - AGENTCARD_TIMEOUT=10
      - LOG_LEVEL=INFO
    restart: unless-stopped
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -s http://localhost:8080/health | jq -e '.status == \"healthy\"' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
