

# UAV-Assisted MEC for Disaster Response: Stackelberg Game-Based Resource Optimization

Yafei Guo\({}^{1}\), Ziye Jia\({}^{1}\), Lei Zhang\({}^{1}\), Jia He\({}^{1}\), Yu Zhang\({}^{2}\), and Qihui Wu\({}^{1}\)

This work was supported in part by National Natural Science Foundation of China under Grant 62301251, in part by the Natural Science Foundation on Frontier Leading Technology Basic Research Project of Jiangsu under Grant BK20222001, in part by the Aeronautical Science Foundation of China 20232071052007, and in part by the Young Elite Scientists Sponsorship Program by CAST 2023QNRC001.

