services:
  # nougat:
  #   build:
  #     context: ./nougat
  #     dockerfile: Dockerfile
  #     target: gpu
  #   image: nougat-gpu
  #   ports:
  #     - "8503:8503"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             capabilities: [gpu]
  #   container_name: nougat
  #   restart: unless-stopped
  #   networks:
  #     - internal-net
    
  # api-gateway:
  #   build:
  #     context: ./nougat/middleware
  #     dockerfile: Dockerfile 
  #   container_name: api-gateway
  #   environment:
  #     - PORT=${PORT}
  #     - NOUGAT_URL=${NOUGAT_URL}
  #     - VALID_API_KEYS=${VALID_API_KEYS}
  #   depends_on:
  #     - nougat
  #   ports:
  #     - "8504:3000"
  #   networks:
  #     macvlan_net:
  #       ipv4_address: 192.168.1.200
  #     internal-net:
  #   cap_add:
  #     - NET_ADMIN
  
  documents-to-text:
    build:
      context: ./documents-to-text
      dockerfile: Dockerfile 
    container_name: documents-to-text
    # depends_on:
    #   - api-gateway
    ports:
      - "8000:8000"
    # networks:
    #   macvlan_net:
    #     ipv4_address: 192.168.1.201
    #   internal-net:
    # cap_add:
    #   - NET_ADMIN

# networks:
#   macvlan_net:
#     driver: macvlan
#     driver_opts:
#       parent: enp0s31f6
#     ipam:
#       config:
#         - subnet: 192.168.1.0/24
#           gateway: 192.168.1.254

#   # Define the internal bridge network for service-to-service communication
#   internal-net:
#     driver: bridge