services:
  nougat:
    build:
      context: ./nougat
      dockerfile: Dockerfile
      target: gpu
    image: nougat-gpu
    ports:
      - "8503:8503"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    container_name: nougat
    restart: unless-stopped
    
  api-gateway:
    build:
      context: ./middleware
      dockerfile: Dockerfile 
    container_name: api-gateway
    ports:
      - "8504:3000" 
    environment:
      - PORT=${PORT}
      - NOUGAT_URL=${NOUGAT_URL}
      - VALID_API_KEYS=${VALID_API_KEYS}
    depends_on:
      - nougat 
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.253


networks:
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: enp0s31f6  # replace with your actual network interface (use `ip a`)
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254
          ip_range: 192.168.1.100/32  # or a broader range