version: '3.8'

services:
  drive-organizer-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: drive-organizer-agent:${VERSION:-latest}
    container_name: drive-organizer-agent
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=8001
      - LOG_LEVEL=INFO
      - WORKER_COUNT=4
    ports:
      - "8001:8001"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G